### ISSUE TITLE
Set up Azure Front Door for non-prod

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/reliable-web-app-pattern-dotnet#219]
Web-facing traffic should flow through a WAF.

## Todo
- [x] remove the boolean surrounding AFD deployment
- [x] modify the createAppRegistration scripts
- update c# code to address AADSTS50011
   - [x] override OnRedirectToIdentityProvider
   - [x] override OnRedirectToIdentityProviderForSignOut
   - [x] create new app config service values AzureAd:FrontDoorPostLogoutRedirectUri & AzureAd:FrontDoorRedirectUri
   - [x] configure asp.net core for proxy
   - [x] update code to explain recommended path of [reverseProxy: host name preservation](https://learn.microsoft.com/en-us/azure/architecture/best-practices/host-name-preservation)
- [x] update guidance (and template) to explain that we deploy AFD for all environments but that we recommend reusing AFD in real scenarios
- [x] update non-prod estimate
