### ISSUE TITLE
Update Azure FrontDoor to Premium

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/reliable-web-app-pattern-dotnet#79]
## Issue
Discovered documentation that states the Azure Front Door option we're using does not provide access to Azure managed rules that provide protection features.

- [OWASP with Anomaly scoring](https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-drs?tabs=drs20#anomaly-scoring-mode)
- [bot protection](https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-policy-configure-bot-protection)

`Only Azure Front Door Premium and Azure Front Door (classic) support managed rules.`
[Web Application Firewall on Azure Front Door](https://learn.microsoft.com/en-us/azure/frontdoor/web-application-firewall)

## TODO
- [x] update the templates to choose Premium sku
- [x] Set the WAF with MSFT managed rules
- [x] update the pricing estimates and review the cost/sla content for updates
- [x] update the guide to callout Premium instead of standard
- [x] work with stephen to update the guide to say that AFD should not be deployed per environment, we just do that for the demo
